"""create_marketplace_settings

Revision ID: 9a12703734a0
Revises: b545938e6381
Create Date: 2026-08-06 23:00:00.575194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a12703734a0'
down_revision: Union[str, Sequence[str], None] = 'b545938e6381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_settings',
    sa.Column('marketplace_name', sa.String(length=255), nullable=False),
    sa.Column('support_email', sa.String(length=255), nullable=False),
    sa.Column('support_phone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('allow_seller_registration', sa.Boolean(), nullable=False),
    sa.Column('default_shipping_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_provider', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_settings_uuid'), 'marketplace_settings', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_settings_uuid'), table_name='marketplace_settings')
    op.drop_table('marketplace_settings')
    # ### end Alembic commands ###
