"""create_bank_accounts_table

Revision ID: b545938e6381
Revises: 3e3c91c29374
Create Date: 2026-08-06 22:34:49.107653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b545938e6381'
down_revision: Union[str, Sequence[str], None] = '3e3c91c29374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_code', sa.String(length=20), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_bank_accounts_uuid'), 'bank_accounts', ['uuid'], unique=True)
    op.add_column('withdrawals', sa.Column('bank_account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'withdrawals', 'bank_accounts', ['bank_account_id'], ['id'])
    op.drop_column('withdrawals', 'bank_name')
    op.drop_column('withdrawals', 'account_name')
    op.drop_column('withdrawals', 'account_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('account_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('withdrawals', sa.Column('account_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('withdrawals', sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'withdrawals', type_='foreignkey')
    op.drop_column('withdrawals', 'bank_account_id')
    op.drop_index(op.f('ix_bank_accounts_uuid'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
